### ISSUE TITLE
PHP 5.6 strict standards error

### ISSUE THREAD

**Issue by andig** [dizews/php-ubjson#2]
Error:

```
PHP Strict standards:  Only variables should be passed by reference in UBJSON.php on line 144
```

Problem: `_encodeString` calls

```
$result = $prefix.$this->_encodeNumeric(strlen($string)).$string;
```

while `_encodeNumeric` expects a variable:

```
protected function _encodeNumeric(&$numeric) {
```

**Comment by dizews** [comment]
Hello, thanks for your submmit.
currently I have not enough time to fix it. It will be a good if you send a pull request.

**Comment by dizews** [comment]
@andig, by the last changes `encodeNumeric` doesn't receive parameters by reference.
does the script work well?

**Comment by dizews** [comment]
not answered. closed it.

**Comment by andig** [comment]
Should be ok as the reference has been removed. Please note: imho references in PHP should not be used as a measure to improve performance. As far as I know copy-on-write is already used in later php versions.

**Comment by dizews** [comment]
thanks.
honestly I do not remember why I have done this.
